[phases.build]
cmds = [
    "mkdir -p bin",
    "cargo build --release --target x86_64-unknown-linux-musl",
    "cp target/x86_64-unknown-linux-musl/release/lppi-data-hub-api bin",
    "cp data/processed_2022.parquet bin/data/processed_2022.parquet",
]
